#!/bin/sh

if [ "$1" = "" ]; then
	echo "Usage> /usr/bin/setcpu <performance | ondemand>"
	exit 1
fi

if [ "$1" = "perf" ]; then
	echo "Setting CPU @ Performance Mode"
	echo "performance" > /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor
else
	if [ "$1" = "performance" ]; then
		echo "Setting CPU @ Performance Mode"
		echo "performance" > /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor
	else
		if [ "$1" = "ondemand" ]; then
			echo "Setting CPU @ Ondemand Mode"
			echo "ondemand" > /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor
		else
			echo "Usage> /usr/bin/setcpu <performance | ondemand>"
			exit 1
		fi
	fi
fi
