#!/bin/sh

[ -r /etc/X11/Xorg.arch-options ] && . /etc/X11/Xorg.arch-options

DISPLAY=":0"
LOGDIR="/var/log"
XORG_CONF=" -config /etc/X11/xorg.conf -configdir /etc/X11/xorg.conf.d "
OTHER_OPTIONS=" -logfile /var/log/Xorg.0.log -ac -noreset +accessx 0 +dpmsphone $XORG_ARCH_OPTS"

# Xorg automatically preserves logs in $LOGDIR/Xorg.DPY.log.(old)


for scriptlet in $(find /etc/X11/arch-preinit.d ! -type d); do
    test -x "$scriptlet" && . "$scriptlet"
done

if [ -e ~/.xinitrc ]; then
	XINITRC=~/.xinitrc
else
	XINITRC=/etc/X11/xinitrc
fi

XSERVER_OPTIONS=" ${DISPLAY} ${OTHER_OPTIONS} ${XORG_CONF} "

if [ "$1" = "--gdb" ]; then
	gdb --args Xorg ${XSERVER_OPTIONS}
else
	if [ "$1" = "--only" ]; then

		Xorg ${XSERVER_OPTIONS} &
	else
		xinit ${XINITRC} -- /usr/bin/Xorg ${XSERVER_OPTIONS} &
	fi
fi

